### ISSUE TITLE
Add Info about payment methods

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#118] opened 2024-02-06 10:11 UTC
### Bootstrap Academy username

Morpheus

### What happened?

In the FAQ Section and before buying, there should be an explanation on how to acquire MorphCoin. Specifically a user wanted us to include how to buy them - with PayPal and Credit Card are our only options and we should clarify that.

**Comment by Lauritz-Tieste** [comment] 2024-05-08 20:18
I could not reproduce a repeating leaderboard. Does this error still occur in the latest version? Can you send a screenshot or a video?

**Comment by engin-karakurt** [comment] 2024-06-23 14:52
Hey There! I wanted to contribute to this Project and fix this issue as a first contribution. Am I just allowed to create my own branch in the frontend repo and fix it? I saw the Job Description but I would like to just do it for fun, I don't want to have a job for it or get pay. Is that fine?

**Comment by Lauritz-Tieste** [comment] 2024-06-23 15:55
Hey, 
It's a great idea to work on this project. If you simply create a fork of the project, you can create a branch on it and submit it as a PullRequest. If the pull request is merged, you will receive the specified bounty as morphcoins at the Academy.

**Comment by engin-karakurt** [comment] 2024-06-23 17:01
Hey thank you for the guidance. Just a question: I have not found anything regarding credit card orders in the code, only PayPal orders. Is this not an option any more or am I missing something? :D

**Comment by Lauritz-Tieste** [comment] 2024-06-23 17:09
![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/84938977/e9398f49-febd-41c9-899c-7f3c2635ca66)

This is what the page where you can buy Morphcoins looks like. With PayPal as payment provider, debit/credit cards are also offered here.

In my opinion, there is no separate payment option without PayPal in between.

**Comment by engin-karakurt** [comment] 2024-06-23 17:46
Got a pull request in, let me know if those changes would be fine! :)

Got another question: Is there a way to login in the local environment or on the preview page that has been deployed, so I can see the changes on a page where i need to authenticate?

**Comment by Lauritz-Tieste** [comment] 2024-06-23 21:13
I don't know if that answers your question correctly, but:
You need a separate account for test instances (localhost, https://test.bootstrap.academy, PR-preview pages) than for live instances (https://bootstrap.academy)

**Comment by engin-karakurt** [comment] 2024-06-23 21:46
Ahh okay, this didn't work for me the first time I tried maybe I overlooked something :^) Now it worked just fine!

I think it would be a good idea I always prefer additional information over not enough, lowers the entry barrier :D

**Comment by Defelo** [comment] 2024-06-23 23:31
> 
> You need to create a separate account for test instances (localhost, https://test.bootstrap.academy, PR-preview pages) and for live instances (https://bootstrap.academy). This are to separated database systems.
> 
> (@Defelo maybe we should include this as a note in the contribution readme)

Yes, that's a good idea. Would you mind creating a pull request for that?

**Comment by engin-karakurt** [comment] 2024-06-24 08:25
Regarding the note in the readme: If you guys don't mind I would be able to do it too!

**Comment by Lauritz-Tieste** [comment] 2024-06-24 08:27
https://github.com/Bootstrap-Academy/frontend/pull/243

**Comment by engin-karakurt** [comment] 2024-06-24 08:30
Oh, didn't see that. Nice!

**Closed** 2024-06-25 15:09 UTC
Labels: bug, frontend
