### ISSUE TITLE
Add AI Integration for explanining quizzes

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#112] opened 2024-01-11 09:44 UTC
### Bootstrap Academy username

Morpheus

### Description

like title. Will do myself

**Comment by Lauritz-Tieste** [comment] 2024-11-02 18:41
duplicate of https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/154

**Closed by Lauritz-Tieste** 2024-11-02 18:41 UTC
Labels: enhancement
