### ISSUE TITLE
Markdown not correctly displayed in Challenge Interface (and likely elsewhere)

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#107] opened 2024-01-10 14:06 UTC
### Bootstrap Academy username

Morpheus

### What happened?

[Here](https://bootstrap.academy/challenges/all?category=0bd5a5b6-f93f-47c4-9e0b-b50d88fb9634&challenge=e01d5764-63a9-4f01-8687-b9c335c6fe97) we can see a challenge description. 
`$2\cdot 2 + 1\cdot 3 = 7$` is not displayed as
$2\cdot 2 + 1\cdot 3 = 7$
is not displayed correctly, however it should. (Just like here)

**Comment by lukaslarndorfer** [comment] 2024-10-27 10:59
I would like to fix this bug

**Comment by Defelo** [comment] 2024-10-27 11:10
Seems to be a duplicate of #76. If you like, you can write a comment there and I can assign you @LLarndorfer

**Closed by Defelo** 2024-10-27 11:10 UTC
Labels: bug
